version: 0.2

phases:
  install:
    commands:
      - echo nothing in the install step
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --environment=ml --target=production
  post_build:
    commands:
      - zip -r dist.zip dist
artifacts:
  files:
    - dist.zip